services:
  - type: static
    name: dr-detection-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist

  - type: web
    name: dr-detection-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: starter

  - type: web
    name: dr-detection-ml-service
    env: docker
    rootDir: ml_service
    dockerfilePath: Dockerfile
    plan: starter
